apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: rnpn-trazabilidad
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME_ROOT_PASSWORD"
  DB_PASSWORD: "CHANGE_ME_DB_PASSWORD"
  DATABASE_URL: "mysql://rnpn_user:CHANGE_ME_DB_PASSWORD@mysql-svc:3306/rnpn_vehiculos_nueva"
  JWT_SECRET: "CHANGE_ME_JWT_SECRET_MINIMO_64_CARACTERES"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "CHANGE_ME"
  SMTP_PASS: "CHANGE_ME"
  SMTP_FROM: "RNPN Vehiculos <notificaciones@rnpn.gob.sv>"
  EMAIL_SUPERVISORES: "CHANGE_ME"
  EMAIL_ADMINS: "CHANGE_ME"
  CLOUDINARY_CLOUD_NAME: "CHANGE_ME"
  CLOUDINARY_API_KEY: "CHANGE_ME"
  CLOUDINARY_API_SECRET: "CHANGE_ME"
